//! MCP server over stdio, exposing worktree operations as tools for AI agents.
//!
//! Register with e.g. `claude mcp add wtm -- wtm mcp` (run from inside the
//! repo). Tool results are the same JSON shapes as the `--json` CLI output.

use std::path::PathBuf;

use anyhow::Result;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::{CallToolResult, ContentBlock, ServerCapabilities, ServerInfo};
use rmcp::{ErrorData, ServerHandler, ServiceExt, schemars, tool, tool_handler, tool_router};
use serde::Deserialize;

use crate::config::Config;
use crate::ops::{self, Ctx};
use crate::output;

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct CreateRequest {
    #[schemars(description = "branch to check out in the new worktree (created if missing)")]
    branch: String,
    #[schemars(description = "base ref for a newly created branch (defaults to HEAD)")]
    from: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct RemoveRequest {
    #[schemars(description = "worktree name (branch name, or directory name when detached)")]
    name: String,
    #[schemars(description = "discard uncommitted changes (default false)")]
    force: Option<bool>,
    #[schemars(description = "also delete the worktree's local branch (default false)")]
    delete_branch: Option<bool>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct NameRequest {
    #[schemars(description = "worktree name (branch name, or directory name when detached)")]
    name: String,
}

/// MCP tool server bound to one repository. The `#[tool_handler]` impl routes
/// tool calls through `Self::tool_router()` generated by `#[tool_router]`.
struct WtmServer {
    repo_root: PathBuf,
}

impl WtmServer {
    /// Reloads config on every call so `.wtm.toml` edits take effect without
    /// restarting the server.
    fn ctx(&self) -> Result<Ctx, ErrorData> {
        let config = Config::load(&self.repo_root).map_err(internal)?;
        Ok(Ctx {
            repo_root: self.repo_root.clone(),
            config,
        })
    }
}

/// Converts any operation error into an MCP internal error.
fn internal(e: impl std::fmt::Display) -> ErrorData {
    ErrorData::internal_error(format!("{e:#}"), None)
}

/// Wraps a serializable result as a JSON text content block.
fn json_result<T: serde::Serialize>(value: &T) -> Result<CallToolResult, ErrorData> {
    let text = serde_json::to_string_pretty(value).map_err(internal)?;
    Ok(CallToolResult::success(vec![ContentBlock::text(text)]))
}

#[tool_router]
impl WtmServer {
    #[tool(
        description = "List all git worktrees with branch, path, dirty file count, and ahead/behind upstream counts"
    )]
    fn list_worktrees(&self) -> Result<CallToolResult, ErrorData> {
        json_result(&ops::list(&self.ctx()?).map_err(internal)?)
    }

    #[tool(
        description = "Create a worktree for a branch (creating the branch if needed), copy configured files, and run the repo's setup commands from .wtm.toml"
    )]
    fn create_worktree(
        &self,
        Parameters(req): Parameters<CreateRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let result = ops::create(&self.ctx()?, &req.branch, req.from.as_deref(), |_| {})
            .map_err(internal)?;
        json_result(&result)
    }

    #[tool(
        description = "Remove a worktree. Refuses when it has uncommitted changes unless force is true"
    )]
    fn remove_worktree(
        &self,
        Parameters(req): Parameters<RemoveRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let delete_branch = req.delete_branch.unwrap_or(false);
        let info = ops::remove(
            &self.ctx()?,
            &req.name,
            req.force.unwrap_or(false),
            delete_branch,
        )
        .map_err(internal)?;
        json_result(&output::remove_json(&info, delete_branch))
    }

    #[tool(description = "List the changed files (staged, unstaged, untracked) in a worktree")]
    fn worktree_status(
        &self,
        Parameters(req): Parameters<NameRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let (info, entries) = ops::status(&self.ctx()?, &req.name).map_err(internal)?;
        json_result(&output::status_json(&info, &entries))
    }

    #[tool(description = "Get the unified diff of a worktree's uncommitted changes")]
    fn worktree_diff(
        &self,
        Parameters(req): Parameters<NameRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let (info, diff) = ops::diff(&self.ctx()?, &req.name).map_err(internal)?;
        json_result(&output::diff_json(&info, &diff))
    }
}

#[tool_handler]
impl ServerHandler for WtmServer {
    fn get_info(&self) -> ServerInfo {
        let mut info = ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_instructions(
                "Manage git worktrees for this repository: create (with automated setup from \
                 .wtm.toml), list, inspect status/diffs, and remove worktrees.",
            );
        info.server_info.name = env!("CARGO_PKG_NAME").into();
        info.server_info.version = env!("CARGO_PKG_VERSION").into();
        info
    }
}

/// Serves MCP over stdio until the client disconnects.
pub fn serve(ctx: Ctx) -> Result<()> {
    let server = WtmServer {
        repo_root: ctx.repo_root,
    };
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()?;
    runtime.block_on(async {
        let service = server.serve(rmcp::transport::stdio()).await?;
        service.waiting().await?;
        Ok(())
    })
}
