//! MCP server over stdio, exposing worktree operations as tools for AI agents.
//!
//! Register with e.g. `claude mcp add wtm -- wtm mcp` (run from inside the
//! repo). Tool results are the same JSON shapes as the `--json` CLI output.

use std::path::PathBuf;

use anyhow::Result;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::{CallToolResult, ContentBlock, ServerCapabilities, ServerInfo};
use rmcp::{ErrorData, ServerHandler, ServiceExt, schemars, tool, tool_handler, tool_router};
use serde::Deserialize;

use crate::config::Config;
use crate::ops::{self, Ctx};
use crate::output;

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct CreateRequest {
    #[schemars(description = "branch to check out in the new worktree (created if missing)")]
    branch: String,
    #[schemars(description = "base ref for a newly created branch (defaults to HEAD)")]
    from: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct RemoveRequest {
    #[schemars(description = "worktree name (branch name, or directory name when detached)")]
    name: String,
    #[schemars(description = "discard uncommitted changes (default false)")]
    force: Option<bool>,
    #[schemars(description = "also delete the worktree's local branch (default false)")]
    delete_branch: Option<bool>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct NameRequest {
    #[schemars(description = "worktree name (branch name, or directory name when detached)")]
    name: String,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct CommitRequest {
    #[schemars(description = "worktree name (branch name, or directory name when detached)")]
    name: String,
    #[schemars(description = "commit message")]
    message: String,
    #[schemars(description = "only stage these paths; defaults to staging every change")]
    paths: Option<Vec<String>>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct StashPushRequest {
    #[schemars(description = "worktree name (branch name, or directory name when detached)")]
    name: String,
    #[schemars(description = "optional stash message")]
    message: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct StashIndexRequest {
    #[schemars(description = "worktree name (branch name, or directory name when detached)")]
    name: String,
    #[schemars(description = "stash entry index (defaults to 0, the most recent)")]
    index: Option<u32>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct PullRequest {
    #[schemars(description = "worktree name (branch name, or directory name when detached)")]
    name: String,
    #[schemars(
        description = "rebase local commits onto the upstream instead of fast-forwarding (default false)"
    )]
    rebase: Option<bool>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct PushRequest {
    #[schemars(description = "worktree name (branch name, or directory name when detached)")]
    name: String,
    #[schemars(
        description = "force-push, but only if the remote hasn't moved unexpectedly (default false)"
    )]
    force_with_lease: Option<bool>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct BranchCreateRequest {
    #[schemars(description = "branch name")]
    name: String,
    #[schemars(description = "base ref for the new branch (defaults to HEAD)")]
    from: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct BranchDeleteRequest {
    #[schemars(description = "branch name")]
    name: String,
    #[schemars(description = "delete even if unmerged, using -D (default false)")]
    force: Option<bool>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct BranchRenameRequest {
    #[schemars(description = "current branch name")]
    old: String,
    #[schemars(description = "new branch name")]
    new: String,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct LogRequest {
    #[schemars(description = "worktree name (branch name, or directory name when detached)")]
    name: String,
    #[schemars(description = "number of commits to show (default 20)")]
    count: Option<u32>,
}

/// MCP tool server bound to one repository. The `#[tool_handler]` impl routes
/// tool calls through `Self::tool_router()` generated by `#[tool_router]`.
struct WtmServer {
    repo_root: PathBuf,
}

impl WtmServer {
    /// Reloads config on every call so `.wtm.toml` edits take effect without
    /// restarting the server. Also re-checks the init gate per call, so the
    /// tools start working the moment `wtm init` runs.
    fn ctx(&self) -> Result<Ctx, ErrorData> {
        let config = Config::load(&self.repo_root).map_err(internal)?;
        let ctx = Ctx {
            repo_root: self.repo_root.clone(),
            config,
        };
        ctx.ensure_initialized().map_err(internal)?;
        Ok(ctx)
    }
}

/// Converts any operation error into an MCP internal error.
fn internal(e: impl std::fmt::Display) -> ErrorData {
    ErrorData::internal_error(format!("{e:#}"), None)
}

/// Wraps a serializable result as a JSON text content block.
fn json_result<T: serde::Serialize>(value: &T) -> Result<CallToolResult, ErrorData> {
    let text = serde_json::to_string_pretty(value).map_err(internal)?;
    Ok(CallToolResult::success(vec![ContentBlock::text(text)]))
}

#[tool_router]
impl WtmServer {
    #[tool(
        description = "List all git worktrees with branch, path, dirty file count, and ahead/behind upstream counts"
    )]
    fn list_worktrees(&self) -> Result<CallToolResult, ErrorData> {
        json_result(&ops::list(&self.ctx()?).map_err(internal)?)
    }

    #[tool(
        description = "Create a worktree for a branch (creating the branch if needed), copy configured files, and run the repo's setup commands from .wtm.toml"
    )]
    fn create_worktree(
        &self,
        Parameters(req): Parameters<CreateRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let result = ops::create(
            &self.ctx()?,
            &req.branch,
            req.from.as_deref(),
            ops::RunMode::Capture,
            |_| {},
        )
        .map_err(internal)?;
        json_result(&result)
    }

    #[tool(
        description = "Remove a worktree. Refuses when it has uncommitted changes unless force is true"
    )]
    fn remove_worktree(
        &self,
        Parameters(req): Parameters<RemoveRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let delete_branch = req.delete_branch.unwrap_or(false);
        let info = ops::remove(
            &self.ctx()?,
            &req.name,
            req.force.unwrap_or(false),
            delete_branch,
        )
        .map_err(internal)?;
        json_result(&output::remove_json(&info, delete_branch))
    }

    #[tool(description = "List the changed files (staged, unstaged, untracked) in a worktree")]
    fn worktree_status(
        &self,
        Parameters(req): Parameters<NameRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let (info, entries) = ops::status(&self.ctx()?, &req.name).map_err(internal)?;
        json_result(&output::status_json(&info, &entries))
    }

    #[tool(description = "Get the unified diff of a worktree's uncommitted changes")]
    fn worktree_diff(
        &self,
        Parameters(req): Parameters<NameRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let (info, diff) = ops::diff(&self.ctx()?, &req.name).map_err(internal)?;
        json_result(&output::diff_json(&info, &diff))
    }

    #[tool(
        description = "Stage and commit changes in a worktree. Stages every change by default, or only the given paths. Use this to save a worktree's in-progress work as a commit"
    )]
    fn commit_changes(
        &self,
        Parameters(req): Parameters<CommitRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let result = ops::commit(&self.ctx()?, &req.name, &req.message, req.paths.as_deref())
            .map_err(internal)?;
        json_result(&result)
    }

    #[tool(
        description = "Stash uncommitted changes (including untracked files) in a worktree, restoring a clean working tree. Use this to set aside in-progress work before switching tasks"
    )]
    fn stash_push(
        &self,
        Parameters(req): Parameters<StashPushRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let result =
            ops::stash_push(&self.ctx()?, &req.name, req.message.as_deref()).map_err(internal)?;
        json_result(&result)
    }

    #[tool(description = "List a worktree's stash entries, newest first")]
    fn stash_list(
        &self,
        Parameters(req): Parameters<NameRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let result = ops::stash_list(&self.ctx()?, &req.name).map_err(internal)?;
        json_result(&result)
    }

    #[tool(
        description = "Apply and drop a stash entry in a worktree (default: the most recent entry). Use this to restore previously stashed work"
    )]
    fn stash_pop(
        &self,
        Parameters(req): Parameters<StashIndexRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let result = ops::stash_pop(&self.ctx()?, &req.name, req.index).map_err(internal)?;
        json_result(&result)
    }

    #[tool(
        description = "Apply a stash entry in a worktree without dropping it (default: the most recent entry). Use this to try out stashed changes while keeping the stash entry"
    )]
    fn stash_apply(
        &self,
        Parameters(req): Parameters<StashIndexRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let result = ops::stash_apply(&self.ctx()?, &req.name, req.index).map_err(internal)?;
        json_result(&result)
    }

    #[tool(
        description = "Delete a stash entry in a worktree without applying it (default: the most recent entry). Use this to discard stashed changes that are no longer needed"
    )]
    fn stash_drop(
        &self,
        Parameters(req): Parameters<StashIndexRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let result = ops::stash_drop(&self.ctx()?, &req.name, req.index).map_err(internal)?;
        json_result(&result)
    }

    #[tool(
        description = "Pull the latest changes for a worktree's branch from its upstream (fast-forward only by default; set rebase to rebase local commits onto the upstream instead). Errors if the branch has no upstream configured"
    )]
    fn pull_worktree(
        &self,
        Parameters(req): Parameters<PullRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let result =
            ops::pull(&self.ctx()?, &req.name, req.rebase.unwrap_or(false)).map_err(internal)?;
        json_result(&result)
    }

    #[tool(
        description = "Push a worktree's branch to its remote, publishing to origin with -u automatically if it has no upstream yet. Set force_with_lease to force-push safely (only if the remote hasn't moved unexpectedly)"
    )]
    fn push_worktree(
        &self,
        Parameters(req): Parameters<PushRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let result = ops::push(
            &self.ctx()?,
            &req.name,
            req.force_with_lease.unwrap_or(false),
        )
        .map_err(internal)?;
        json_result(&result)
    }

    #[tool(
        description = "Fetch every remote for the repo and prune deleted remote-tracking branches"
    )]
    fn fetch_remotes(&self) -> Result<CallToolResult, ErrorData> {
        json_result(&ops::fetch(&self.ctx()?).map_err(internal)?)
    }

    #[tool(
        description = "List local branches with upstream tracking, ahead/behind counts, last-commit info, and which worktree (if any) has each checked out"
    )]
    fn list_branches(&self) -> Result<CallToolResult, ErrorData> {
        json_result(&ops::branch_list(&self.ctx()?).map_err(internal)?)
    }

    #[tool(
        description = "Create a local branch without checking it out in a worktree. Use create_worktree instead when the branch needs a working directory right away"
    )]
    fn create_branch(
        &self,
        Parameters(req): Parameters<BranchCreateRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let result =
            ops::branch_create(&self.ctx()?, &req.name, req.from.as_deref()).map_err(internal)?;
        json_result(&result)
    }

    #[tool(
        description = "Delete a local branch. Refuses if it's checked out in a worktree (remove that worktree first) or unmerged, unless force is true"
    )]
    fn delete_branch(
        &self,
        Parameters(req): Parameters<BranchDeleteRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let result = ops::branch_delete(&self.ctx()?, &req.name, req.force.unwrap_or(false))
            .map_err(internal)?;
        json_result(&result)
    }

    #[tool(description = "Rename a local branch")]
    fn rename_branch(
        &self,
        Parameters(req): Parameters<BranchRenameRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let result = ops::branch_rename(&self.ctx()?, &req.old, &req.new).map_err(internal)?;
        json_result(&result)
    }

    #[tool(description = "Show recent commits (newest first) for a worktree's branch")]
    fn worktree_log(
        &self,
        Parameters(req): Parameters<LogRequest>,
    ) -> Result<CallToolResult, ErrorData> {
        let result =
            ops::log(&self.ctx()?, &req.name, req.count.unwrap_or(20)).map_err(internal)?;
        json_result(&result)
    }
}

#[tool_handler]
impl ServerHandler for WtmServer {
    fn get_info(&self) -> ServerInfo {
        let mut info = ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_instructions(
                "Manage git worktrees for this repository: create (with automated setup from \
                 .wtm.toml), list, inspect status/diffs, and remove worktrees. Also supports \
                 per-worktree commits, stashes, pulls, and pushes, plus repo-wide fetch and \
                 branch management (list/create/delete/rename) and commit history.",
            );
        info.server_info.name = env!("CARGO_PKG_NAME").into();
        info.server_info.version = env!("CARGO_PKG_VERSION").into();
        info
    }
}

/// Serves MCP over stdio until the client disconnects.
pub fn serve(ctx: Ctx) -> Result<()> {
    let server = WtmServer {
        repo_root: ctx.repo_root,
    };
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()?;
    runtime.block_on(async {
        let service = server.serve(rmcp::transport::stdio()).await?;
        service.waiting().await?;
        Ok(())
    })
}
